//based on the example generated by the App...

let serial;
let latestData = "waiting for data";

let xCoord;
let prevXCoord;
let yCoord;
let prevYCoord;

let portName = 'COM3';//update this with the port you are using

let oldAcc;

let acc = [];

function setup() {
 createCanvas(windowWidth, windowHeight);
	background(255,255,255)

	xCoord = width/2;
	yCoord = height/2;

 serial = new p5.SerialPort();

 //serial.list();
 serial.open(portName);

 serial.on('connected', serverConnected);

 serial.on('list', gotList);

 serial.on('data', gotData);

 serial.on('error', gotError);

 serial.on('open', gotOpen);

 serial.on('close', gotClose);
}

function serverConnected() {
 print("Connected to Server");
}

function gotList(thelist) {
 print("List of Serial Ports:");

 for (let i = 0; i < thelist.length; i++) {
  print(i + " " + thelist[i]);
 }
}

function gotOpen() {
 print("Serial Port is Open");
}

function gotClose(){
 print("Serial Port is Closed");
 latestData = "Serial Port is Closed";
}

function gotError(theerror) {
 print(theerror);
}

function gotData() {
 let currentString = serial.readLine();
  trim(currentString);//trim removes white spaces
 if (!currentString) return;
 //console.log(currentString);
 latestData = currentString.split(',');
 console.log(latestData);

 acc[0]= map(latestData[2],-2,2,0,100);
  acc[1]= map(latestData[3],-2,2,0,100);
 acc[2]= map(latestData[4],-2,2,0,100);

}

function draw() {
//background(255);
 prevXCoord = xCoord;
xCoord = constrain(map(latestData[0],0,1023,0,width),0,width);

 prevYCoord = yCoord;
yCoord = constrain(map(latestData[1],0,1023,0,height),0,height);
 

 stroke(0);
 strokeWeight(5);
 line(prevXCoord, prevYCoord,xCoord,yCoord);
/*
 noStroke();
 fill(255,0,0);
 rect(0,0,20,acc[0])
 fill(0,255,0);
  rect(20,0,20,acc[1])

 fill(0,0,255);
  rect(40,0,20,acc[2])*/

  eraseIt();

}


function keyPressed(){
	if(key == 'l'){
		writeSerial(key);
	}
}

function writeSerial(writeOut){
	serial.write(writeOut);
}

function eraseIt(){

	if(acc[1]-oldAcc > 100){
		background(255);
		oldAcc = acc[1];
	}

	oldAcc = acc[1];
}